### ISSUE TITLE
checking upstream changes fails when upstream branch is not configured

### ISSUE THREAD

**Issue by kevna** [kevna/statusline#1]
# steps to replicate:
- create a new local branch (not fetching or pushing to set upstream)
- run statusline
## expected outcome:
display the result: `~/r/e/positorybranch`
## actual outcome:
fails with errocode 1 and traceback:
```
Traceback (most recent call last):
  File "/home/amoore/.local/bin/statusline", line 8, in <module>
    sys.exit(main())
  File "/home/amoore/.local/lib/python3.8/site-packages/statusline/__main__.py", line 5, in main
    print(DirectoryMinify().get_statusline())
  File "/home/amoore/.local/lib/python3.8/site-packages/statusline/status.py", line 36, in get_statusline
    return self._apply_vcs(path)
  File "/home/amoore/.local/lib/python3.8/site-packages/statusline/status.py", line 30, in _apply_vcs
    + self.VCS.short_stats() \
  File "/home/amoore/.local/lib/python3.8/site-packages/statusline/git.py", line 95, in short_stats
    ab = self.ahead_behind()
  File "/home/amoore/.local/lib/python3.8/site-packages/statusline/git.py", line 71, in ahead_behind
    ahead = self._count(["rev-list", "@{u}..HEAD"])
  File "/home/amoore/.local/lib/python3.8/site-packages/statusline/git.py", line 31, in _count
    results = self._run_command(command).split("\n")
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by kevna** [comment]
# temporary solution:
Push the branch to upstream immediately following it's creation using `git push --set-upstream origin <branchname>`.
This creates and assigns the remote branch as upstream which may be suboptimal depending on workflow

# cause notes
- When no upstream branch exists the command `git rev-list @{u}..HEAD` fails with errorcode 128 and message `fatal: no upstream configured for branch <branchname>`
- Git._run_command catches and hides failures by returning None in these cases
- Git._count expects Git._run_command to always return a string and thus errors trying to split NoneType

**Comment by kevna** [comment]
# Possible solutions:
we can keep this existing behaviour of _run_command and update make sure that when called we handle the None case sensibly (eg. _count could return 0)

we can change _run_command to always return string (returning "" in the errorcase) this obfuscates the error case more completely and may have impact on future features

alternatively we could remove the error-hiding behavior from _run_command which would force the places that call it to handle the error - this will likely lead to duplicating the existing errorhandling throughout the calling functions but makes it more explicit that this is an error case

## potential future development
as long as we can still distinguish the error from the blank cases then we could update in the future to show a warning indicator if the upstream is not currently assigned (as this is distinct from being in-sync with the upstream)
